### ISSUE TITLE
Panasonic Thick Film Resistors

### ISSUE THREAD

**Issue by fireballmatt** [mikelawrence/RPi-Hat-Thermocouple#1]
It looks like both Mouser and DigiKey have run out of stock on some of the 3EKF series SMD TFR's (namely 1001V and 4701V) with something like 30-40 weeks lead time on restock.

Panasonic has released the new PB3B series of the 1001V and 4701V's. Not sure if they are intended as replacements or not.

Are these drop in replacements? 

- [ERJ-PV3B1001V](http://www.mouser.com/ProductDetail/Panasonic/ERJ-PB3B1001V/?qs=sGAEpiMZZMu61qfTUdNhG3eCjCAbg%2fKZJqoPB2Il0tIBeRGUdyohSg%3d%3d)
- [ERJ-PV3B4701V](http://www.mouser.com/ProductDetail/Panasonic/ERJ-PB3B4701V/?qs=sGAEpiMZZMu61qfTUdNhG3eCjCAbg%2fKZzvZ7YeX62qqPmpW5FPCskw%3d%3d)

**Comment by mikelawrence** [comment]
The resistors you asked about will work fine but they are the rather expensive 0.1% tolerance. Honestly any 0603 resistor will work fine for this design including 5% tolerance. 

This one from Yageo will work fine [RC0603FR-074K7L](http://www.mouser.com/ProductDetail/Yageo/RC0603FR-074K7L/?qs=sGAEpiMZZMukHu%252bjC5l7YfGIerj%2fLQjm068PC2%252b1rxU%3d) and is cheaper.

**Comment by fireballmatt** [comment]
Thanks Mike!
